### ISSUE TITLE
image builder template deploys unnecessary example application

### ISSUE THREAD

**Issue by dhellmann** [ansible-collections/edge.microshift#34]
##### SUMMARY

The default image_builder role should not deploy an example application.

The template at https://github.com/ansible-collections/edge.microshift/blob/main/roles/image_builder/templates/lvms_setup.j2 builds an example application. It was probably based on some instructions in the documentation showing how to use the LVMS system for an app that needed a PVC, but users do not need that app in every deployment.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles/image_builder

##### ANSIBLE VERSION

N/A

##### COLLECTION VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

N/A

##### EXPECTED RESULTS

Only a user's applications are included in their ostree images.

**Comment by matoval** [comment]
Thank you @dhellmann for pointing this issue out, I'll adjust the template to only add an application when a user provides one to add and remove the test one we currently have in the vars.
